name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run efficiency tests
        run: |
          PYTHONPATH=$PWD pytest tests/test_performance.py -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ONEHAA }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_ONEHAA }}/nlp-api:latest

  deploy:
    needs: build-and-push
    # Self-hosted runner를 사용하도록 지정
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ONEHAA }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_ONEHAA }}/nlp-api:latest

      - name: Stop and remove old container
        run: |
          docker stop nlp-server || true
          docker rm nlp-server || true

      - name: Run new container
        run: |
          docker run -d --name nlp-server -p 8000:8000 ${{ secrets.DOCKERHUB_ONEHAA }}/nlp-api:latest
