name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_ONEHAA }}/nlp-api:latest .

      - name: Run efficiency tests (Inside Sandbox)
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_ONEHAA }}/nlp-api:latest pytest tests/test_performance.py -v

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_ONEHAA }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_ONEHAA }}/nlp-api:latest

      - name: Deploy Local (Stop, Remove, Run)
        run: |
          docker stop nlp-server || true
          docker rm nlp-server || true
          docker run -d --name nlp-server -p 8000:8000 ${{ secrets.DOCKERHUB_ONEHAA }}/nlp-api:latest
